In [1]:
import json
import pandas as pd
data_file = open("yelp_academic_dataset_review.json")
# review = []
# for line in data_file:
#     review.append(json.loads(line))
# checkin_df = pd.DataFrame(review)
# data_file.close()

In [2]:
data_file

In [3]:
review=[]
for line in data_file:
    #line = data_file.readline()
    review.append(json.loads(line))
review_df = pd.DataFrame(review)
data_file.close()

In [4]:
review_df.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,lWC-xP3rd6obsecCYsGZRg,ak0TdVmGKo4pwqdJSTLwWw,buF9druCkbuXLX526sGELQ,4.0,3,1,1,Apparently Prides Osteria had a rough summer a...,2014-10-11 03:34:02
1,8bFej1QE5LXp4O05qjGqXA,YoVfDbnISlW0f7abNQACIg,RA4V8pr014UyUbDvI-LW2A,4.0,1,0,0,This store is pretty good. Not as great as Wal...,2015-07-03 20:38:25
2,NDhkzczKjLshODbqDoNLSg,eC5evKn1TWDyHCyQAwguUw,_sS2LBIGNT5NQb6PD1Vtjw,5.0,0,0,0,I called WVM on the recommendation of a couple...,2013-05-28 20:38:06
3,T5fAqjjFooT4V0OeZyuk1w,SFQ1jcnGguO0LYWnbbftAA,0AzLzHfOJgL7ROwhdww2ew,2.0,1,1,1,I've stayed at many Marriott and Renaissance M...,2010-01-08 02:29:15
4,sjm_uUcQVxab_EeLCqsYLg,0kA0PAJ8QFMeveQWHFqz2A,8zehGz9jnxPqXtOc7KaJxA,4.0,0,0,0,The food is always great here. The service fro...,2011-07-28 18:05:01

In [16]:
review_df.to_csv("review_df.csv",index=False)

In [202]:
review_df["sum_ufc"]=review_df["useful"]+review_df["funny"]+review_df["cool"]

In [7]:
review_df_withufc=review_df[review_df["sum_ufc"]>0]

In [8]:
review_df_withufc.shape

(4371109, 10)

In [203]:
review_df_non=review_df[review_df["useful"].apply(lambda x: x==0) & 
                        review_df["funny"].apply(lambda x: x==0) & 
                        review_df["cool"].apply(lambda x: x==0)]

In [204]:
review_df_non_s=review_df_non

In [205]:
review_df_non_s.loc[review_df_non_s["funny"] <= 10, "funny_label"] =0

In [206]:
review_df_non_s.loc[review_df_non_s["useful"] <= 10, "useful_label"] =0

In [207]:
review_df_non_s.loc[review_df_non_s["cool"] <= 10, "cool_label"] =0

In [208]:
review_df_non_s_len=review_df_non_s[review_df_non_s["text"].apply(lambda x: len(x)>256)]

In [209]:
review_df_non_s_len_s=review_df_non_s_len.sample(n=10000)

In [210]:
review_df_non_s_len_s.shape

(10000, 13)

In [68]:
review_df_u=review_df[review_df["useful"]>10]

In [69]:
review_df_u.shape

(120866, 10)

In [70]:
review_df_f=review_df[review_df["funny"]>10]

In [71]:
review_df_f.shape

(35152, 10)

In [72]:
review_df_c=review_df[review_df["cool"]>10]

In [73]:
review_df_c.shape

(42901, 10)

In [ ]:
review_df_u

In [74]:
review_ufc=pd.concat([review_df_u,review_df_f,review_df_c])

In [75]:
review_ufc.loc[review_ufc["useful"] > 10, "useful_label"] =1
review_ufc.loc[review_ufc["useful"] <= 10, "useful_label"] =0

In [77]:
review_ufc.loc[review_ufc["funny"] > 10, "funny_label"] =1
review_ufc.loc[review_ufc["funny"] <= 10, "funny_label"] =0

In [78]:
review_ufc.loc[review_ufc["cool"] > 10, "cool_label"] =1
review_ufc.loc[review_ufc["cool"] <= 10, "cool_label"] =0

In [88]:
review_ufc

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,sum_ufc,useful_label,funny_label,cool_label
171,vmdZ24Us8xE5ddWJQJ2Pdg,QTwk5Ij2D0lwz851-SFqdw,TnRcGRybKUR5phkN7Es3jQ,4.0,12,8,12,"I was surprised when I read the reviews of MM,...",2017-06-17 16:58:56,32,1.0,0.0,1.0
174,2UOV2P08kWY1OphhG2AnhA,BRJY7e_ywYO7FpUpSHxpew,0Ng-wDNyA-96uaJZP8EKZg,5.0,49,1,1,"Neil England is a true ""Ink God"". I Googled be...",2015-03-18 18:15:01,51,1.0,0.0,0.0
239,3VZR28H98yG79kftnchqqw,ihj8ppHpHsfjHJFNyy9ahA,FYQHebkSHB0DE3xbn3f7Yg,1.0,13,0,1,An open letter to Kreuger Farms:\n\nDear Mr. K...,2013-06-24 07:14:55,14,1.0,0.0,0.0
477,BcfiuNFEot14i1VQ3uI_GQ,Ri1nrLjmtQoDLnULZal3PA,sLkK9Ofmk9UFDrjXxh3iLA,4.0,27,20,25,Sampling Lab is in a nice space. It is a ways...,2015-08-19 12:05:26,72,1.0,1.0,1.0
735,tytfY-T1IQsx6ptSY2qX_w,ARKuqLyU06-GNvmmb2wj_Q,YB7mBTPgHRSq_MGr2UQ1qA,4.0,12,1,7,Pijiu belly is new restaurant in Westside that...,2014-12-17 18:39:32,20,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8635125,8B_KzCUbipqnCO3TspfFfw,j-W_qFmY-vGFCzFfNVQJ-Q,K2XwYhodpeGWW6T57bZ88Q,5.0,22,10,18,I've been to many Asian grocery stores here in...,2020-09-12 00:12:05,50,1.0,0.0,1.0
8635175,ob1DWeY67Lx185aYDigAfQ,ePX43507yLh5LqGm6XGbCQ,d27P-HGCTjuBL3fWjWl7IA,5.0,17,8,12,Just cluckin perfection let me tell you. I've ...,2020-03-25 19:09:12,37,1.0,0.0,1.0
8635219,dNakfxwK-44LfBqQxRYTag,a4mO387_O77ebmv8AlQB3A,UJt9GsEpDi-zBK-Lp3deCA,3.0,55,28,46,The Wawa invasion continues across Florida and...,2019-01-13 03:17:32,129,1.0,1.0,1.0
8635288,XPmHutE_kOIX8eKxsGK33g,pl6TrMiSEmaAMCqA_HL6kw,GlwENG4gC8XKKJ2sPZ3b7A,5.0,15,7,15,"We were visiting Portland, OR for a family vac...",2019-11-19 11:07:17,37,1.0,0.0,1.0
8635400,7vNXRIClt-9rFzMXlrtMXA,tr13Jb83h2itjyXVwaO5eA,rbuj2X4SXIc3MDul4dcxIA,5.0,39,13,34,"Yummy, great chew on the bagel\nFriendly staff...",2020-06-13 02:39:26,86,1.0,1.0,1.0

In [151]:
review_ufc_unique=review_ufc.drop_duplicates()

In [152]:
review_ufc_unique.shape

(133557, 13)

In [153]:
review_ufc_unique.reset_index(inplace=True,drop=True)

In [154]:
review_ufc_unique.shape

(133557, 13)

In [155]:
review_ufc_len=review_ufc_unique[review_ufc_unique["text"].apply(lambda x: len(x)>256)]

In [156]:
review_ufc_len.shape

(126704, 13)

In [157]:
review_ufc_len.head(5)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,sum_ufc,useful_label,funny_label,cool_label
0,vmdZ24Us8xE5ddWJQJ2Pdg,QTwk5Ij2D0lwz851-SFqdw,TnRcGRybKUR5phkN7Es3jQ,4.0,12,8,12,"I was surprised when I read the reviews of MM,...",2017-06-17 16:58:56,32,1.0,0.0,1.0
1,2UOV2P08kWY1OphhG2AnhA,BRJY7e_ywYO7FpUpSHxpew,0Ng-wDNyA-96uaJZP8EKZg,5.0,49,1,1,"Neil England is a true ""Ink God"". I Googled be...",2015-03-18 18:15:01,51,1.0,0.0,0.0
2,3VZR28H98yG79kftnchqqw,ihj8ppHpHsfjHJFNyy9ahA,FYQHebkSHB0DE3xbn3f7Yg,1.0,13,0,1,An open letter to Kreuger Farms:\n\nDear Mr. K...,2013-06-24 07:14:55,14,1.0,0.0,0.0
3,BcfiuNFEot14i1VQ3uI_GQ,Ri1nrLjmtQoDLnULZal3PA,sLkK9Ofmk9UFDrjXxh3iLA,4.0,27,20,25,Sampling Lab is in a nice space. It is a ways...,2015-08-19 12:05:26,72,1.0,1.0,1.0
4,tytfY-T1IQsx6ptSY2qX_w,ARKuqLyU06-GNvmmb2wj_Q,YB7mBTPgHRSq_MGr2UQ1qA,4.0,12,1,7,Pijiu belly is new restaurant in Westside that...,2014-12-17 18:39:32,20,1.0,0.0,0.0

In [158]:
review_ufc_len_u=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==1) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==0)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==0)]

In [159]:
review_ufc_len_u.shape

(72778, 13)

In [160]:
review_ufc_len_uf=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==1) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==1)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==0)]

In [161]:
review_ufc_len_uf.shape

(4293, 13)

In [162]:
review_ufc_len_ufc=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==1) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==1)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==1)]

In [163]:
review_ufc_len_ufc.shape

(19880, 13)

In [164]:
review_ufc_len_uc=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==1) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==0)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==1)]

In [165]:
review_ufc_len_uc.head(5)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,sum_ufc,useful_label,funny_label,cool_label
0,vmdZ24Us8xE5ddWJQJ2Pdg,QTwk5Ij2D0lwz851-SFqdw,TnRcGRybKUR5phkN7Es3jQ,4.0,12,8,12,"I was surprised when I read the reviews of MM,...",2017-06-17 16:58:56,32,1.0,0.0,1.0
13,yrRYAxjnAT2A4zEQwGHIVg,m07sy7eLtOjVdZ8oN9JKag,tqywh0jPNukMEvWlO7QufQ,4.0,12,7,11,So we had well over an hour before our little ...,2018-07-07 21:05:06,30,1.0,0.0,1.0
19,sn9SQDmQzaXkAoxwmYfakQ,RqR1bGDgdOPyHDnI73LeFw,H53_vmbw_LrmbR5gaF5dhw,4.0,19,10,12,* Solid HK style cafe *\n\nThis spot which use...,2010-10-05 23:03:59,41,1.0,0.0,1.0
24,WnDyS55wihE72zoRi7z71Q,ZY2HuOTauUiYgOE_Ee5o3Q,x49canS-pbLxFV5577x0gA,5.0,20,0,19,"I admit, I'm a sucker for cute little places l...",2011-06-29 14:34:13,39,1.0,0.0,1.0
27,btPP-F4Hvq0wNS3zoObrCw,pnTiEaqM4slogpY97n9Kvg,LniaQ-j3OG_qzaNSrewsbg,5.0,19,4,16,"Gorgeous, inspiring, and vibrant art murals sp...",2018-03-15 19:55:42,39,1.0,0.0,1.0

In [166]:
review_ufc_len_uc.shape

(18242, 13)

In [167]:
review_ufc_len_fc=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==0) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==1)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==1)]

In [168]:
review_ufc_len_fc.shape

(730, 13)

In [169]:
review_ufc_len_f=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==0) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==1)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==0)]

In [170]:
review_ufc_len_f.shape

(8515, 13)

In [171]:
review_ufc_len_c=review_ufc_len[review_ufc_len["useful_label"].apply(lambda x: x==0) & 
                                review_ufc_len["funny_label"].apply(lambda x: x==0)& 
                                review_ufc_len["cool_label"].apply(lambda x: x==1)]

In [172]:
review_ufc_len_c.shape

(2266, 13)

In [214]:
review_ufc_len_u_sel=review_ufc_len_u.sample(n=20000)

In [216]:
review_cleaned=pd.concat([review_df_non_s_len_s,review_ufc_len_u_sel,review_ufc_len_uf,
                          review_ufc_len_uc,review_ufc_len_ufc,review_ufc_len_f,
                         review_ufc_len_fc,review_ufc_len_c],sort=False)

In [217]:
review_cleaned.shape

(83926, 13)

In [218]:
review_cleaned.head(5)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,sum_ufc,funny_label,useful_label,cool_label
8633129,1YkaVE4vKrUG4U0gaU2gVQ,dSJsIiZ-4tukQlzh6lqoHA,N8dxdQ8rcTggVfo34Mqd3A,5.0,0,0,0,After leaving Rooms 2 Go and left with both st...,2020-05-12 21:18:10,0,0.0,0.0,0.0
2649150,tRm3Q9gvgbwbko7A3HM66Q,EjeNnnZSQBxAKULRmX3ORA,XlTWGrMdZ8iNt1T0HSiAOQ,3.0,0,0,0,I've been here a few times. In general the foo...,2012-04-03 05:28:46,0,0.0,0.0,0.0
4173677,dAr-P9mG_ss1EZpYECB1lQ,TdE14X6G42RzVa3NnBYWXQ,jYp3f4Fy_TTLrPseaPWMiQ,4.0,0,0,0,Had the pork belly entree & it was yummy! Don...,2020-02-21 01:48:36,0,0.0,0.0,0.0
2594794,-wlnDJUuxZmgFVa0ZWmMMA,Sz1xO7IxH7D4FjiHkP9cow,AVx0lohaIerkMzIEUKL6xg,1.0,0,0,0,"I walked into this store, and there were few c...",2017-12-29 20:35:49,0,0.0,0.0,0.0
2420621,K6GfClzmIeioWILr1-m4Jw,qMifgObSkBD_vnVe65rKdw,jPdGmHBTbZXcIgP8fnVdaw,1.0,0,0,0,"I sat for 15 mins in the lobby, nobody work he...",2019-04-27 14:17:17,0,0.0,0.0,0.0

In [219]:
review_cleaned.to_csv("review_cleaned.csv",index=False)

In [13]:
review=[]
for i in range(10):
    line = data_file.readline()
    review.append(json.loads(line))
review_df = pd.DataFrame(review)
data_file.close()

In [14]:
review_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,lWC-xP3rd6obsecCYsGZRg,ak0TdVmGKo4pwqdJSTLwWw,buF9druCkbuXLX526sGELQ,4.0,3,1,1,Apparently Prides Osteria had a rough summer a...,2014-10-11 03:34:02
1,8bFej1QE5LXp4O05qjGqXA,YoVfDbnISlW0f7abNQACIg,RA4V8pr014UyUbDvI-LW2A,4.0,1,0,0,This store is pretty good. Not as great as Wal...,2015-07-03 20:38:25
2,NDhkzczKjLshODbqDoNLSg,eC5evKn1TWDyHCyQAwguUw,_sS2LBIGNT5NQb6PD1Vtjw,5.0,0,0,0,I called WVM on the recommendation of a couple...,2013-05-28 20:38:06
3,T5fAqjjFooT4V0OeZyuk1w,SFQ1jcnGguO0LYWnbbftAA,0AzLzHfOJgL7ROwhdww2ew,2.0,1,1,1,I've stayed at many Marriott and Renaissance M...,2010-01-08 02:29:15
4,sjm_uUcQVxab_EeLCqsYLg,0kA0PAJ8QFMeveQWHFqz2A,8zehGz9jnxPqXtOc7KaJxA,4.0,0,0,0,The food is always great here. The service fro...,2011-07-28 18:05:01
5,J4a2TuhDasjn2k3wWtHZnQ,RNm_RWkcd02Li2mKPRe7Eg,xGXzsc-hzam-VArK6eTvtw,1.0,2,0,0,"This place used to be a cool, chill place. Now...",2018-01-21 04:41:03
6,28gGfkLs3igtjVy61lh77Q,Q8c91v7luItVB0cMFF_mRA,EXOsmAB1s71WePlQk0WZrA,2.0,0,0,0,"The setting is perfectly adequate, and the foo...",2006-04-16 02:58:44
7,9vqwvFCBG3FBiHGmOHMmiA,XGkAG92TQ3MQUKGX9sLUhw,DbXHNl890xSXNiyRczLWAg,5.0,0,0,0,Probably one of the better breakfast sandwiche...,2017-12-02 18:16:13
8,2l_TDrQ7p-5tANOyiOlkLQ,LWUnzwK0ILquLLZcHHE1Mw,mD-A9KOWADXvfrZfwDs-jw,4.0,1,0,0,I am definitely a fan of Sports Authority. Th...,2012-05-28 15:00:47
9,KKVFopqzcVfcubIBxmIjVA,99RsBrARhhx60UnAC4yDoA,EEHhKSxUvJkoPSzeGKkpVg,5.0,0,0,0,I work in the Pru and this is the most afforda...,2014-05-07 18:10:21

In [37]:
review_df["text"][2]

"I called WVM on the recommendation of a couple of friends who had used them in the past and thought they did a nice job. I'm a fan now, too.\n\nEvan and Cody showed up right on time for my move this past weekend. They were friendly and energetic, working quickly but carefully to get all my things moved out of the old place and into the new one in less than 2.5 hours. All of my (heavy) furniture arrived in perfect condition, and they took extra care not to scratch the wood floors in the process.\n\nI hope not to move again anytime soon, but next time I do, I'll be calling WVM."

In [38]:
review_df["text"][0]

"Apparently Prides Osteria had a rough summer as evidenced by the almost empty dining room at 6:30 on a Friday night. However new blood in the kitchen seems to have revitalized the food from other customers recent visits. Waitstaff was warm but unobtrusive. By 8 pm or so when we left the bar was full and the dining room was much more lively than it had been. Perhaps Beverly residents prefer a later seating. \n\nAfter reading the mixed reviews of late I was a little tentative over our choice but luckily there was nothing to worry about in the food department. We started with the fried dough, burrata and prosciutto which were all lovely. Then although they don't offer half portions of pasta we each ordered the entree size and split them. We chose the tagliatelle bolognese and a four cheese filled pasta in a creamy sauce with bacon, asparagus and grana frita. Both were very good. We split a secondi which was the special Berkshire pork secreto, which was described as a pork skirt steak with garlic potato purée and romanesco broccoli (incorrectly described as a romanesco sauce). Some tables received bread before the meal but for some reason we did not. \n\nManagement also seems capable for when the tenants in the apartment above began playing basketball she intervened and also comped the tables a dessert. We ordered the apple dumpling with gelato and it was also quite tasty. Portions are not huge which I particularly like because I prefer to order courses. If you are someone who orders just a meal you may leave hungry depending on you appetite. Dining room was mostly younger crowd while the bar was definitely the over 40 set. Would recommend that the naysayers return to see the improvement although I personally don't know the former glory to be able to compare. Easy access to downtown Salem without the crowds on this month of October."

In [19]:
tip_file=open("yelp_academic_dataset_tip.json")

tip=[]
for i in range(10):
    line = tip_file.readline()
    tip.append(json.loads(line))
tip_df = pd.DataFrame(tip)
tip_file.close()

In [20]:
tip_df

,user_id,business_id,text,date,compliment_count
0,WCjg0jdHXMlwbqS9tZUx8Q,ENwBByjpoa5Gg7tKgxqwLg,Carne asada chips...,2011-07-22 19:07:35,0
1,42-Z02y9bABShAGZhuSzrQ,jKO4Og6ucdX2-YCTKQVYjg,Best happy hour from 3pm to 6pm! $1 off martin...,2014-09-10 07:33:29,0
2,5u7E3LYp_3eB8dLuUBazXQ,9Bto7mky640ocgezVKSfVg,"Nice people, skilled staff, clean location - b...",2013-12-13 23:23:41,0
3,wDWoMG5N9oI4DJ-p7z8EBg,XWFjKtRGZ9khRGtGg2ZvaA,"1/2-price bowling & the ""Very"" Old Fashion are...",2017-07-11 23:07:16,0
4,JmuFlorjjRshHTKzTwNtgg,mkrx0VhSMU3p3uhyJGCoWA,"Solid gold's. Great sauna. Great staff, too. E...",2016-11-30 08:46:36,0
5,MHmKe1NQ1pCpIrbK4XREDw,VQftVUvHfMQdDTmnO0iQqg,Try a few different styles and instructors of ...,2010-03-22 21:40:26,0
6,S5tOE7JAvaeXBEibnAV02g,2PxZ-fICnd432NJHefXrcA,On The Border was very fresh and fast for non-...,2011-10-08 17:14:20,0
7,fTsVDajAyDJ-YzsSdfXSDw,oQyf1788YWsiDLupGva6sw,Cold cuts are the best,2015-06-09 14:35:57,0
8,g3HFkZgloxLQCvoJ5Zs5gg,OQ2oHkcWA8KNC1Lsvj1SBA,Water Ave coffee served here--& @ L Jeans!,2018-03-22 15:28:09,0
9,sNVpZLDSlCudlXLsnJpg7A,Wqetc51pFQzz04SXh_AORA,So busy...,2014-06-07 12:09:55,0

In [46]:
bus_file=open("yelp_academic_dataset_business.json")
bus=[]
for i in range(300,330):
    line = bus_file.readline()
    bus.append(json.loads(line))
bus_df = pd.DataFrame(bus)
bus_file.close()

In [47]:
bus_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,1,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
2,bvN78flM8NLprQ1a1y5dRg,The Reclaimory,4720 Hawthorne Ave,Portland,OR,97214,45.511907,-122.613693,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Antiques, Fashion, Used, Vintage & Consignment...","{'Thursday': '11:0-18:0', 'Friday': '11:0-18:0..."
3,oaepsyvc0J17qwi8cfrOWg,Great Clips,2566 Enterprise Rd,Orange City,FL,32763,28.914482,-81.295979,3.0,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Hair Salons",None
4,PE9uqAjdw0E4-8mjGl3wVA,Crossfit Terminus,1046 Memorial Dr SE,Atlanta,GA,30316,33.747027,-84.353424,4.0,14,1,"{'GoodForKids': 'False', 'BusinessParking': '{...","Gyms, Active Life, Interval Training Gyms, Fit...","{'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'..."
5,D4JtQNTI4X3KcbzacDJsMw,Bob Likes Thai Food,3755 Main St,Vancouver,BC,V5V,49.251342,-123.101333,3.5,169,1,"{'GoodForKids': 'True', 'Alcohol': 'u'none'', ...","Restaurants, Thai","{'Monday': '17:0-21:0', 'Tuesday': '17:0-21:0'..."
6,t35jsh9YnMtttm69UCp7gw,Escott Orthodontics,2511 Edgewater Dr,Orlando,FL,32804,28.573998,-81.389284,4.5,7,1,"{'AcceptsInsurance': 'True', 'BusinessAcceptsC...","Dentists, Health & Medical, Orthodontists","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:30', ..."
7,jFYIsSb7r1QeESVUnXPHBw,Boxwood Biscuit,740 S High St,Columbus,OH,43206,39.947007,-82.997471,4.5,11,1,None,"Breakfast & Brunch, Restaurants","{'Saturday': '8:0-14:0', 'Sunday': '8:0-14:0'}"
8,N3_Gs3DnX4k9SgpwJxdEfw,Lane Wells Jewelry Repair,"7801 N Lamar Blvd, Ste A140",Austin,TX,78752,30.346169,-97.711458,5.0,30,1,"{'RestaurantsPriceRange2': '1', 'ByAppointment...","Shopping, Jewelry Repair, Appraisal Services, ...","{'Monday': '12:15-17:0', 'Tuesday': '12:15-17:..."
9,tXvdYGvlEceDljN8gt2_3Q,Capital City Barber Shop,"615 W Slaughter Ln, Ste 113",Austin,TX,78748,30.172706,-97.799920,4.0,5,0,"{'BusinessAcceptsCreditCards': 'False', 'Resta...","Barbers, Beauty & Spas","{'Monday': '9:0-17:0', 'Tuesday': '9:0-19:0', ..."
10,rYs_1pNB_RMtn5WQh55QDA,Chautauqua General Store,100 Clematis Dr,Boulder,CO,80302,39.998449,-105.281006,3.5,5,1,"{'BikeParking': 'True', 'RestaurantsTakeOut': ...","Food, Shopping, Convenience Stores, Souvenir S...","{'Monday': '8:0-20:0', 'Tuesday': '8:0-20:0', ..."
11,hCABMnKtwo4Y9alQDxh2kw,Star Kreations Salon and Spa,"124 Newbury St, Unit C",Peabody,MA,01960,42.534248,-70.990948,4.0,8,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Wigs, Hair Extensions, Hair Salons, Blow Dry/O...","{'Monday': '10:0-15:0', 'Tuesday': '9:0-18:0',..."
12,HPA_qyMEddpAEtFof02ixg,Mr G's Pizza & Subs,474 Lowell St,Peabody,MA,01960,42.541155,-70.973438,4.0,39,1,"{'RestaurantsGoodForGroups': 'True', 'HasTV': ...","Food, Pizza, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
13,ufCxltuh56FF4-ZFZ6cVhg,Sister Honey's,247 E Michigan St,Orlando,FL,32806,28.513265,-81.374707,4.5,135,1,"{'BusinessParking': '{'garage': False, 'street...","Restaurants, American (New), Bakeries, Dessert...","{'Tuesday': '11:0-18:0', 'Wednesday': '11:0-18..."
14,i_t_30RYVUDdZzFIcw80NQ,Uncle Sam's Pawn Shop,225 E Main St,Columbus,OH,43215,39.956615,-82.993302,4.0,5,0,"{'BusinessParking': '{'garage': False, 'street...","Books, Mags, Music & Video, Musical Instrument...","{'Tuesday': '9:0-17:30', 'Wednesday': '9:0-17:..."
15,g7CEhqBIpwTg6ERcMkCmrQ,Finish Line Car Wash,5510 Memorial Dr,Stone Mountain,GA,30083,33.800687,-84.212820,2.5,11,1,{'BusinessAcceptsCreditCards': 'True'},"Oil Change Stations, Smog Check Stations, Auto...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
16,GfWJ19Js7wX9rwaHQ7KbGw,Everything POP Shopping & Dining,1050 Century Dr,Orlando,FL,32830,28.350498,-81.542819,3.0,7,1,"{'HasTV': 'False', 'Caters': 'False', 'Busines...","Restaurants, American (New), Food Court, Flowe...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-22:0', '..."
17,MUeUyqhMja-nnmvgP4rBBg,Saratoga Resort Villas,4787 W Irlo Bronson Hwy,Kissimmee,FL,34746,28.330255,-81.469464,3.5,55,0,"{'WiFi': ''free'', 'RestaurantsPriceRange2': '...","Hotels, Vacation Rentals, Hotels & Travel, Eve...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
18,6fT0lYr_UgWSCZs_w1PBTQ,Salter School,2 Florence St,Malden,MA,02148,42.427889,-71.073475,2.0,5,1,None,"Specialty Schools, Massage Schools, Middle Sch...","{'Monday': '8:0-20:0', 'Tuesday': '8:0-20:0', ..."
19,dmbbf3AqeG61_QHRZi1M1w,RaceTrac,350 W Sand Lake Rd,Pine Castle,FL,32809,28.450302,-81.380587,3.5,5,1,"{'BikeParking': 'False', 'RestaurantsPriceRang...","Automotive, American (Traditional), Gas Statio...",None
20,DLbEQySMW3X7KvkybpEYkw,Jasmine Nail Spa,"4370 SE King Rd, Ste 125",Portland,OR,97222,45.447598,-122.617427,3.0,7,0,"{'RestaurantsPriceRange2': '1', 'ByAppointment...","Nail Salons, Beauty & Spas","{'Monday': '9:30-18:0', 'Tuesday': '9:30-18:0'..."
21,AvT2mGkdYwU0ghqDfs-OlQ,Tire Town Auto Service,2032 Hastings Street E,Vancouver,BC,V5L 1T8,49.281059,-123.063019,4.0,6,0,None,"Auto Repair, Automotive, Tires","{'Monday': '9:0-17:30', 'Tuesday': '9:0-17:30'..."
22,ynTjh_FdhbG5hY69HsEoaA,Cascade Restaurant,"Hyatt Regency Grand Cypress, 1 Grand Cypress Blvd",Orlando,FL,32836,28.381945,-81.510327,3.5,18,0,"{'OutdoorSeating': 'True', 'RestaurantsAttire'...","Hotels, American (Traditional), Restaurants, E...","{'Monday': '7:0-22:0', 'Tuesday': '7:0-22:0', ..."
23,j68RDnvOaYEwGcY9cTEHpA,Pittock Mansion,3229 NW Pittock Dr,Portland,OR,97210,45.525259,-122.716227,4.5,406,1,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Tours, Museums, Architectural Tours, Venues & ...","{'Monday': '0:0-0:0', 'Thursday': '10:0-16:0',..."
24,nTIhpR7MhsALPwg_Hh14EA,DoubleTree by Hilton Hotel Austin,6505 N Interstate 35,Austin,TX,78752,30.326377,-97.704543,3.0,139,1,"{'WiFi': 'u'free'', 'RestaurantsPriceRange2': ...","Hotels, Hotels & Travel, Event Planning & Serv...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
25,Y2ojrodkbEheGttZF8wYEQ,Wolf Camera and Image,3141 Piedmont Rd NE,Atlanta,GA,30305,33.842808,-84.370455,3.5,15,0,"{'BusinessParking': '{'garage': False, 'street...","Shopping, Photography Stores & Services","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
26,hcRxdDg7DYryCxCoI8ySQA,Longwood Galleria,340-350 Longwood Ave,Boston,MA,02215,42.338544,-71.106842,2.5,24,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Restaurants, Shopping, Shopping Centers","{'Monday': '6:30-22:0', 'Tuesday': '6:30-22:0'..."
27,8XyEpVdAO0o6iVkVxkWosQ,PS Property Management Company,"2506 S Lamar Blvd, Ste 2",Austin,TX,78704,30.246465,-97.778738,4.5,9,1,{'BusinessAcceptsCreditCards': 'True'},"Home Services, Real Estate, Property Management","{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ..."
28,arEXRZYu8220bFBJ3VAh3A,Blake's On The Park,227 10th St NE,Atlanta,GA,30309,33.781475,-84.379955,3.5,170,1,"{'Alcohol': ''full_bar'', 'BusinessParking': '...","Nightlife, Bars, Gay Bars, Sports Bars","{'Monday': '15:0-3:0', 'Tuesday': '15:0-3:0', ..."
29,jGennaZUr2MsJyRhijNBfA,Legal Sea Foods,1 Harborside Dr,Boston,MA,02128,42.363442,-71.025781,3.5,856,1,"{'NoiseLevel': 'u'average'', 'BikeParking': 'F...","Sandwiches, Food, Restaurants, Breakfast & Bru...","{'Monday': '6:0-21:0', 'Tuesday': '6:0-21:0', ..."

In [24]:
bus_df["attributes"][0]

{'RestaurantsTableService': 'True',
 'WiFi': "u'free'",
 'BikeParking': 'True',
 'BusinessParking': "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}",
 'BusinessAcceptsCreditCards': 'True',
 'RestaurantsReservations': 'False',
 'WheelchairAccessible': 'True',
 'Caters': 'True',
 'OutdoorSeating': 'True',
 'RestaurantsGoodForGroups': 'True',
 'HappyHour': 'True',
 'BusinessAcceptsBitcoin': 'False',
 'RestaurantsPriceRange2': '2',
 'Ambience': "{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': False, 'upscale': False, 'classy': False, 'casual': True}",
 'HasTV': 'True',
 'Alcohol': "'beer_and_wine'",
 'GoodForMeal': "{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}",
 'DogsAllowed': 'False',
 'RestaurantsTakeOut': 'True',
 'NoiseLevel': "u'average'",
 'RestaurantsAttire': "'casual'",
 'RestaurantsDelivery': 'None'}

In [25]:
bus_df["attributes"][1]

{'RestaurantsTakeOut': 'True',
 'RestaurantsAttire': "u'casual'",
 'GoodForKids': 'True',
 'BikeParking': 'False',
 'OutdoorSeating': 'False',
 'Ambience': "{'romantic': False, 'intimate': False, 'touristy': False, 'hipster': False, 'divey': False, 'classy': False, 'trendy': False, 'upscale': False, 'casual': True}",
 'Caters': 'True',
 'RestaurantsReservations': 'False',
 'RestaurantsDelivery': 'False',
 'HasTV': 'False',
 'RestaurantsGoodForGroups': 'False',
 'BusinessAcceptsCreditCards': 'True',
 'NoiseLevel': "u'average'",
 'ByAppointmentOnly': 'False',
 'RestaurantsPriceRange2': '2',
 'WiFi': "u'free'",
 'BusinessParking': "{'garage': True, 'street': False, 'validated': False, 'lot': False, 'valet': False}",
 'Alcohol': "u'beer_and_wine'",
 'GoodForMeal': "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': False, 'breakfast': True}"}

In [26]:
bus_df["attributes"][2]

{'BusinessAcceptsCreditCards': 'True',
 'RestaurantsPriceRange2': '2',
 'ByAppointmentOnly': 'False',
 'BikeParking': 'False',
 'BusinessParking': "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}"}

In [29]:
ci_file=open("yelp_academic_dataset_checkin.json")
ci=[]
for i in range(10):
    line = ci_file.readline()
    ci.append(json.loads(line))
ci_df = pd.DataFrame(ci)
ci_file.close()

In [30]:
ci_df

              business_id                                               date
0  --0r8K_AQ4FZfLsX3ZYRDA                                2017-09-03 17:13:59
1  --0zrn43LEaB4jUWTQH_Bg  2010-10-08 22:21:20, 2010-11-01 21:29:14, 2010...
2  --164t1nclzzmca7eDiJMw  2010-02-26 02:06:53, 2010-02-27 08:00:09, 2010...
3  --2aF9NhXnNVpDV0KS3xBQ  2014-11-03 16:35:35, 2015-01-30 18:16:03, 2015...
4  --2mEJ63SC_8_08_jGgVIg  2010-12-15 17:10:46, 2013-12-28 00:27:54, 2015...
5  --6COJIAjkQwSUZci_4PJQ  2012-09-23 20:58:03, 2012-10-08 22:49:59, 2012...
6  --DzGwfuJH12DjYz95VW0Q           2014-08-02 14:12:55, 2015-02-21 17:37:57
7  --EoF6KmeDuki2vBWhPqCw           2012-08-27 21:10:37, 2012-09-21 22:35:50
8  --JKSSgnfoOjVDFGv692BA  2011-08-15 22:43:08, 2015-11-16 13:19:35, 2017...
9  --JuLhLvq3gyjNnXT9Q95w                                2016-06-08 15:40:03

In [31]:
user_file=open("yelp_academic_dataset_user.json")
user=[]
for i in range(10):
    line = user_file.readline()
    user.append(json.loads(line))
user_df = pd.DataFrame(user)
user_file.close()

In [32]:
user_df

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,q_QQ5kBBwlCcbL1s4NVK3g,Jane,1220,2005-03-14 20:26:35,15038,10030,11291,"2006,2007,2008,2009,2010,2011,2012,2013,2014","xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357,...,163,190,361,147,1212,5691,2541,2541,815,323
1,dIIKEfOgo0KqUfGQvGikPg,Gabi,2136,2007-08-10 19:01:51,21272,10289,18046,"2007,2008,2009,2010,2011,2012,2013,2014,2015,2...","XPzYf9_mwG2eXYP2BAGSTA, 2LooM5dcIk2o01nftYdPIg...",1025,...,87,94,232,96,1187,3293,2205,2205,472,294
2,D6ErcUnFALnCQN4b1W_TlA,Jason,119,2007-02-07 15:47:53,188,128,130,"2010,2011","GfB6sC4NJQvSI2ewbQrDNA, jhZtzZNNZJOU2YSZ6jPlXQ...",16,...,1,3,0,0,5,20,31,31,3,1
3,JnPIjvC0cmooNDfsa9BmXg,Kat,987,2009-02-09 16:14:29,7234,4722,4035,"2009,2010,2011,2012,2013,2014","HQZPQhKMwRAyS6BCselVWQ, kP2U1s_sjQfHO9grxiyDTA...",420,...,129,93,219,90,1120,4510,1566,1566,391,326
4,37Hc8hr3cw0iHLoPzLK6Ow,Christine,495,2008-03-03 04:57:05,1577,727,1124,"2009,2010,2011","-Q88pZUcrfN0BLBDp-bkAQ, etPn4Pv1Gc4cRZjRgB_BOw...",47,...,19,32,16,15,77,131,310,310,98,44
5,n-QwITZYrXlKQRiV30MqNg,Natasha,229,2008-06-25 14:53:17,476,101,140,"2010,2011,2012,2013,2014,2015,2016","2ptwW5l68069vNtW8J-WOg, 4TVFuz8L4TsDtx_ObSin9g...",17,...,4,3,0,0,10,15,24,24,16,2
6,eCJoZqpV1fDKJGAsXmWXqQ,Bridget,51,2009-07-22 16:47:01,53,14,16,,"DlT1HhrcYfDhjJNUyskU5g, C0ly5C7RzTlzh0M55YspDw...",1,...,0,0,0,0,3,1,2,2,1,0
7,cojecOwQJpsYDxnjtgzteQ,Steven,51,2010-07-04 17:18:40,136,47,44,"2010,2011","_Tpd51CSlnOyvDTpOtgG5w, jVYzrVblDFSuL3GHtt8ZSA...",4,...,5,2,1,0,4,6,12,12,4,2
8,1jXmzuIFKxTnEnR0pxO0Hg,Clara,299,2010-10-01 17:29:36,381,106,121,"2010,2011,2012,2013,2014,2015","VGfzq5na6LZUwxwWO5eVLA, 35uHDsVOEsWbLdEg8Ttobg...",23,...,8,2,6,0,17,47,30,30,4,1
9,-8QoOIfvwwxJ4sY201WP5A,Antoinette,288,2007-08-04 20:21:09,752,220,306,"2012,2013,2014,2015,2016,2017,2018","vePby1OhpTiQiX75XrN97A, UG8cewYtZdep2hzSekIqYg...",25,...,4,6,2,0,12,32,24,24,11,2

In [35]:
bus_df["attributes"][8]

{'RestaurantsPriceRange2': '1',
 'ByAppointmentOnly': 'False',
 'BusinessParking': "{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}",
 'BusinessAcceptsCreditCards': 'True',
 'DogsAllowed': 'True',
 'RestaurantsDelivery': 'None',
 'BusinessAcceptsBitcoin': 'False',
 'BikeParking': 'True',
 'RestaurantsTakeOut': 'None',
 'WheelchairAccessible': 'True'}